name: Handle stale issues and PRs
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is stale because it hasn't seen any activity in the last year. Remove stale label or comment or this will be closed in 60 days."
          stale-pr-message: "This PR is stale because it hasn't seen any activity in the last 4 months. Remove stale label or comment or this will be closed in 30 days."
          close-issue-message: 'This issue was closed because it has been stalled for 60 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity.'
          days-before-issue-stale: 365
          days-before-pr-stale: 120
          days-before-issue-close: 60
          days-before-pr-close: 30
